name: 01 build

on:
  repository_dispatch:
    types: [run-another] 
  workflow_dispatch:
    inputs:
      package:
        description: 'Config number'     
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
          arch: [armv6,armv7,aarch64,amd64,s390x,ppc64le,mips64le,i386]
          distro: [bullseye]
          include:
            - arch: riscv64
              distro: unstable
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare host
        run: |
            sudo apt-get purge -y dotnet* gfortran gfortran* android-sdk
            sudo apt install curl wget grep
            sudo rm -r /usr/share/dotnet/ /usr/local/lib/android/sdk
            export CURR=$(([ -z "${{ github.event.inputs.package }}" ] && echo ${{github.event.client_payload.number}})||echo ${{ github.event.inputs.package }})
            echo $CURR
            echo "PREV=$(($CURR-1))" >> $GITHUB_ENV
            echo "NEXT=$(($CURR+1))" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        name: Checkout
      - name: Download artifact
        uses: GarnetOS/action-download-artifact@new
        with:
          workflow: prepare.yml
          name: out-${{matrix.arch}}-${{env.PREV}}
      - name: Prepare image
        run: |
            pwd
            sudo ls
            sudo apt install -y util-linux wget zip
            sudo mkdir /mnt/lfs
            sudo mount VHD.img /mnt/lfs
            sudo ls 
      - uses: GarnetOS/run-on-arch-action@v2.1.2
        name: Download and release
        with:
          arch: ${{matrix.arch}}
          distro: ${{matrix.distro}}
          setup: |
            
          dockerRunArgs: |
            --volume "/mnt/lfs:/mnt/lfs"
            --volume "${PWD}/01:${PWD}/01"
          run: |
            uname -a
            apt update
            apt install -y wget zip util-linux timelimit
            apt install -y gcc g++ gzip libc6 grep make patch perl python3 sed tar xz-utils binutils bison bzip2 coreutils diffutils findutils gawk texinfo
            rm /bin/sh
            ln -s /bin/bash /bin/sh
            export LFS=/mnt/lfs
            useradd -m -s /bin/bash lfs
            chmod +x -R 01
            cd 01
            chown lfs prepare
            ./timeout su lfs './${{github.event.inputs.package}}'
      - uses: actions/upload-artifact@v2
        with:
          name: out-${{matrix.arch}}-${{github.event.inputs.package}}
          path: VHD.img
  post:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare host
        run: |
            export CURR=$(([ -z "${{ github.event.inputs.package }}" ] && echo ${{github.event.client_payload.number}})||echo ${{ github.event.inputs.package }})
            echo $CURR
            echo "PREV=$(($CURR-1))" >> $GITHUB_ENV
            echo "NEXT=$(($CURR+1))" >> $GITHUB_ENV
      #- name: Repository Dispatch
      #  uses: peter-evans/repository-dispatch@v1
      #  with:
      #    token: ${{ secrets.TOKEN }}
      #    event-type: run-another
      #    client-payload: '{"number": "${{ env.NEXT }}"}'
