name: 02 to 03 permissions
 
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
          arch: [armv6,armv7,aarch64,amd64,ppc64le,i386]
          distro: [bullseye]
    #      include:
    #        - arch: riscv64
    #          distro: unstable
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare host
        run: |
            sudo apt-get purge -y dotnet* gfortran gfortran* android-sdk
            sudo apt install curl wget grep
            sudo rm -r /usr/share/dotnet/ /usr/local/lib/android/sdk
            wget https://dl.min.io/client/mc/release/linux-amd64/archive/mcli_20220426180022.0.0_amd64.deb
            sudo dpkg -i mcli_20220426180022.0.0_amd64.deb
            mcli alias set myminio/ http://${{ secrets.MINIO_IP }}:9000 ${{ secrets.MINIO_ACCESS }} ${{ secrets.MINIO_SECRET }}
            export CURR=$(([ -z "${{ github.event.inputs.package }}" ] && echo ${{github.event.client_payload.number}})||echo ${{ github.event.inputs.package }})
            echo "CURR=$(($CURR))" >> $GITHUB_ENV
            echo "PREV=$(($CURR-1))" >> $GITHUB_ENV
            echo "NEXT=$(($CURR+1))" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        name: Checkout
      - name: Download
        run: |
            mcli cp myminio/bucket/out-${{matrix.arch}}.tar.gz out.tar.gz
      #- name: Download artifact
      #  uses: GarnetOS/action-download-artifact@new
      #  with:
      #    workflow: 02.yml
      #    name: out-${{matrix.arch}}-25
      - name: Prepare image
        run: |
            pwd
            sudo ls
            sudo apt install -y util-linux wget zip
            tar -xvf out.tar.gz
            rm out.tar.gz
            sudo mkdir /mnt/lfs
            sudo mount -o suid VHD.img /mnt/lfs
            export LFS=/mnt/lfs
            if [[ -f "/mnt/lfs/usr/bin/env" ]]; then
              echo "Env exists."
            else
              exit 1
            fi
            sudo ls 
            sudo chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
            case ${{matrix.arch}} in
              *64) sudo chown -R root:root $LFS/lib64 ;;
              *64le) sudo chown -R root:root $LFS/lib64 ;;
            esac
            sudo mkdir -pv $LFS/{dev,proc,sys,run}
            sudo mknod -m 600 $LFS/dev/console c 5 1
            sudo mknod -m 666 $LFS/dev/null c 1 3
            cd /mnt/lfs
            tar -czvf out.tar.gz VHD.img
            tar -tzf out.tar.gz > /dev/null
      - name: Rename
        run: mv out.tar.gz out-${{matrix.arch}}.tar.gz
      - name: Minio install and deploy
        run: |
            mcli cp out-${{matrix.arch}}.tar.gz myminio/bucket
      - uses: actions/upload-artifact@v2
        with:
          name: out-${{matrix.arch}}-26
          path: VHD.img
