name: 02 to 03 permissions
 
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Config number'     
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
          arch: [armv6,armv7,aarch64,amd64,s390x,ppc64le,mips64le,i386]
          distro: [bullseye]
          include:
            - arch: riscv64
              distro: unstable
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare host
        run: |
            sudo apt-get purge -y dotnet* gfortran gfortran* android-sdk
            sudo apt install curl wget grep
            sudo rm -r /usr/share/dotnet/ /usr/local/lib/android/sdk
            export CURR=$(([ -z "${{ github.event.inputs.package }}" ] && echo ${{github.event.client_payload.number}})||echo ${{ github.event.inputs.package }})
            echo "CURR=$(($CURR))" >> $GITHUB_ENV
            echo "PREV=$(($CURR-1))" >> $GITHUB_ENV
            echo "NEXT=$(($CURR+1))" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        name: Checkout
      - name: Download artifact
        uses: GarnetOS/action-download-artifact@new
        with:
          workflow: 0203.yml
          name: out-${{matrix.arch}}-${{env.PREV}}
      - name: Prepare image
        run: |
            pwd
            sudo ls
            sudo apt install -y util-linux wget zip
            sudo mkdir /mnt/lfs
            sudo mount -o suid VHD.img /mnt/lfs
            export LFS=/mnt/lfs
            sudo ls 
            sudo chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
            case ${{matrix.arch}} in
              *64) sudo chown -R root:root $LFS/lib64 ;;
            esac
            sudo mkdir -pv $LFS/{dev,proc,sys,run}
            sudo mknod -m 600 $LFS/dev/console c 5 1
            sudo mknod -m 666 $LFS/dev/null c 1 3
      - uses: actions/upload-artifact@v2
        with:
          name: out-${{matrix.arch}}-${{env.CURR}}
          path: VHD.img
