name: 03 build

on:
  repository_dispatch:
    types: [run-another-3]
  workflow_dispatch:
    inputs:
      package:
        description: 'Config number'     
        required: true
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
          arch: [armv6,armv7,aarch64,i386,amd64]
          distro: [bullseye]
#          include:
#            - arch: riscv64
#              distro: unstable
    runs-on: ubuntu-latest
    steps:
      - name: Prepare host
        run: |
            sudo apt-get purge -y dotnet* gfortran gfortran* android-sdk
            sudo apt install curl wget grep util-linux cpulimit
            sudo rm -r /usr/share/dotnet/ /usr/local/lib/android/sdk
            wget https://dl.min.io/client/mc/release/linux-amd64/archive/mcli_20220426180022.0.0_amd64.deb
            sudo dpkg -i mcli_20220426180022.0.0_amd64.deb
            sudo fallocate -l 6G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            mcli alias set myminio/ http://${{ secrets.MINIO_IP }}:9000 ${{ secrets.MINIO_ACCESS }} ${{ secrets.MINIO_SECRET }}
            export CURR=$(([ -z "${{ github.event.inputs.package }}" ] && echo ${{github.event.client_payload.number}})||echo ${{ github.event.inputs.package }})
            echo "CURR=$(($CURR))" >> $GITHUB_ENV
            echo "PREV=$(($CURR-1))" >> $GITHUB_ENV
            echo "NEXT=$(($CURR+1))" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        name: Checkout
      #- name: Download artifact
      #  uses: GarnetOS/action-download-artifact@new
      #  with:
      #    workflow: 0203.yml
      #    name: out-${{matrix.arch}}-${{env.PREV}}
      - name: Download
        run: |
            mcli cp myminio/bucket/out-${{matrix.arch}}.tar.gz out.tar.gz
      - name: Prepare image
        run: |
            pwd
            sudo ls
            sudo apt install -y util-linux wget zip
            sudo mkdir /mnt/lfs
            tar -xvf out.tar.gz
            sudo mount -o suid VHD.img /mnt/lfs
            sudo ls 
      - uses: GarnetOS/run-on-arch-action@v2.1.2
        name: Download and release
        with:
          arch: ${{matrix.arch}}
          distro: ${{matrix.distro}}
          setup: |
            
          dockerRunArgs: |
            --volume "/mnt/lfs:/mnt/lfs"
            --volume "${PWD}/03:${PWD}/03"
          run: |
            uname -a
            apt update
            apt install -y wget zip util-linux timelimit sudo cpulimit
            apt install -y gcc g++ gzip libc6 grep make patch perl python3 sed tar xz-utils binutils bison bzip2 coreutils diffutils findutils gawk texinfo
            rm /bin/sh
            ln -s /bin/bash /bin/sh
            export LFS=/mnt/lfs
            chmod +x -R 03
            cd 03
            cp ${{env.CURR}} $LFS/
            sudo ./prepare
            sudo cpulimit -l 95 -e sudo ./timeout sudo chroot /mnt/lfs /usr/bin/env -i   \
            HOME=/root                  \
            TERM="$TERM"                \
            PATH=/usr/bin:/usr/sbin     \
            ./${{env.CURR}}
      - name: Unmount
        run: |
            sleep 1m
            sudo umount /mnt/lfs           
      - name: Prepare image
        run: |
               tar -czvf out.tar.gz VHD.img
               tar -tzf out.tar.gz >/dev/null
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: out-${{matrix.arch}}-${{env.CURR}}
          path: out.tar.gz
      - name: Rename
        run: mv out.tar.gz out-${{matrix.arch}}.tar.gz
      - name: Minio deploy
        run: |
            sleep 30s
            mcli cp out-${{matrix.arch}}.tar.gz myminio/bucket
  post:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare host
        run: |
            export CURR=$(([ -z "${{ github.event.inputs.package }}" ] && echo ${{github.event.client_payload.number}})||echo ${{ github.event.inputs.package }})
            echo $CURR
            echo "PREV=$(($CURR-1))" >> $GITHUB_ENV
            echo "NEXT=$(($CURR+1))" >> $GITHUB_ENV
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          event-type: run-another-3
          client-payload: '{"number": "${{ env.NEXT }}"}'
