# This is a basic workflow to help you get started with Actions

name: Artifact test

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        arch: [armv6,armv7,aarch64,i386,amd64]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: GarnetOS/run-on-arch-action@v2.1.1
        name: Download and release
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
        with:
          arch: ${{matrix.arch}}
          distro: buster
          setup: |
            mkdir -p "${PWD}/out"
          dockerRunArgs: |
            --volume "${PWD}/out:/out"
          run: |
            uname -a
            apt update
            apt install -y wget zip
            cd out
            dd if=/dev/zero of=VHD.img bs=1G count=10
      - uses: actions/upload-artifact@v2
        with:
          name: out-${{matrix.arch}}
          path: out/VHD.img
