# This is a basic workflow to help you get started with Actions

name: Download packages

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv6,armv7,aarch64]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Download and release
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
        with:
          arch: ${{matrix.arch}}
          distro: buster
          setup: |
            mkdir -p "${PWD}/out"
          dockerRunArgs: |
            --volume "${PWD}/out:/out"
          run: |
            mkdir src
            cd src
            wget https://www.linuxfromscratch.org/lfs/downloads/stable/wget-list
            wget --input-file=wget-list --continue --directory-prefix=.
            cd ..
            zip src-${{matrix.arch}} src
            mv src-${{matrix.arch}} out
      - name: Upload
        run: |
           gh release upload v1.0 out/src-${{ matrix.arch }} -R GarnetOS/Core
          
            
