# This is a basic workflow to help you get started with Actions

name: Download build artifacts

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
          arch: [armv6,armv7,aarch64,amd64,s390x,ppc64le,mips64le,i386]
          distro: [bullseye]
          include:
            - arch: riscv64
              distro: unstable
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make more space
        run: |
            sudo apt-get purge -y dotnet* gfortran gfortran* android-sdk
            sudo rm -r /usr/share/dotnet/ /usr/local/lib/android/sdk
      - uses: actions/checkout@v2
        name: Checkout
      - name: Download artifact
        uses: GarnetOS/action-download-artifact@v2.16.0
        with:
          workflow: testzip.yml
          name: out-test
      - name: Prepare image
        run: |
            sudo apt install -y util-linux wget zip
            sudo mkdir /mnt/lfs
            sudo mount VHD.img /mnt/lfs
      - uses: GarnetOS/run-on-arch-action@v2.1.2
        name: Download and release
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
        with:
          arch: ${{matrix.arch}}
          distro: ${{matrix.distro}}
          setup: |
            
          dockerRunArgs: |
            --volume "/mnt/lfs:/mnt/lfs"
          run: |
            ls /mnt/lfs
