on:
  workflow_dispatch:
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Disk
        run: |
            df -h
            #sudo du -a / | sort -n -r | head -n 20
            sudo apt-get purge -y dotnet* gfortran gfortran* android-sdk
            sudo rm -r /usr/share/dotnet/ /usr/local/lib/android/sdk
            dotnet --list-sdks
            df -h
            sudo du -a / | sort -n -r | head -n 20
      - name: CPU & RAM
        run: |
            lscpu
            grep MemTotal /proc/meminfo
      - name: list
        run: ls -l
