on:
  workflow_dispatch:
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Disk
        run: |
            df -h
            sudo du -a / | sort -n -r | head -n 20
            sudo apt-get purge -y dotnet* gfortran gfortran*
            sudo rm -r /usr/share/dotnet/
            #dotnet --list-sdks
            df -h
