name: Test of Arch
on:
  workflow_dispatch:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: sudo apt update; sudo apt-get install qemu binfmt-support qemu-user-static
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/debian:testing
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 2
    steps:
      - name: Check for dockerenv file
        run: uname -a
