# This is a basic workflow to help you get started with Actions

name: Test ZIP

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Prepare image
        run: |
            sudo apt install -y util-linux wget zip
            sudo fallocate -l 25M VHD.img 
            sudo mkfs -v -t ext4 VHD.img
      - uses: actions/upload-artifact@v2
        with:
          name: out-test
          path: VHD.img
